title: "Trevelr"
email: jacahal+trevelr@gmail.com
timezone: UTC
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-CBXE8Q7M3G

# Authors
authors:
  jon:
    name: Jon
    display_name: Jon
    avatar: 'assets/images/jon.jpeg'
    email: jacahal+trevelr@gmail.com
    instagram: https://www.instagram.com/trevelr_blog/
    description: "Trevelr in chief, coffee connoisseur, and amateur story teller."

# Social
social:
  instagram: https://www.instagram.com/trevelr_blog/
  discord: https://discord.gg/B5BbcSPC

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-admin
